// prettier-ignore
import { AC, AD, AE, AF, AG, AI, AL, AM, AO, AQ, AR, AS, AT, AU, AW, AX, AZ, BA, BB, BD, BE, BF, BG, BH, BI, BJ, BL, BM, BN, BO, BQ, BR, BS, BT, BV, BW, BY, BZ, CA, CC, CD, CF, CG, CH, CI, CK, CL, CM, CN, CO, CR, CU, CV, CW, CX, CY, CZ, DE, DJ, DK, DM, DO, DZ, EC, EE, EG, EH, ER, ES, ET, EU, FI, FJ, FK, FM, FO, FR, GA, GB, GD, GE, GF, GG, GH, GI, GL, GM, GN, GP, GQ, GR, GS, GT, GU, GW, GY, HK, HM, HN, HR, HT, HU, IC, ID, IE, IL, IM, IN, IO, IQ, IR, IS, IT, JE, JM, JO, JP, KE, KG, KH, KI, KM, KN, KP, KR, KW, KY, KZ, LA, LB, LC, LI, LK, LR, LS, LT, LU, LV, LY, MA, MC, MD, ME, MF, MG, MH, MK, ML, MM, MN, MO, MP, MQ, MR, MS, MT, MU, MV, MW, MX, MY, MZ, NA, NC, NE, NF, NG, NI, NL, NO, NP, NR, NU, NZ, OM, PA, PE, PF, PG, PH, PK, PL, PM, PN, PR, PS, PT, PW, PY, QA, RE, RO, RS, RU, RW, SA, SB, SC, SD, SE, SG, SH, SI, SJ, SK, SL, SM, SN, SO, SR, SS, ST, SV, SX, SY, SZ, TA, TC, TD, TF, TG, TH, TJ, TK, TL, TM, TN, TO, TR, TT, TV, TW, TZ, UA, UG, UM, US, UY, UZ, VA, VC, VE, VG, VI, VN, VU, WF, WS, XK, YE, YT, ZA, ZM, ZW } from 'country-flag-icons/react/3x2';

export type CountryKey = keyof typeof countries
export type CountryName = CountryEntry['name']

type CountryEntry = {
  name: string
  component: React.ComponentType
}

export const countries: Record<string, CountryEntry> = {
  ascensionIsland: { name: 'Ascension Island', component: AC },
  andorra: { name: 'Andorra', component: AD },
  unitedArabEmirates: { name: 'United Arab Emirates', component: AE },
  afghanistan: { name: 'Afghanistan', component: AF },
  antiguaAndBarbuda: { name: 'Antigua and Barbuda', component: AG },
  anguilla: { name: 'Anguilla', component: AI },
  albania: { name: 'Albania', component: AL },
  armenia: { name: 'Armenia', component: AM },
  angola: { name: 'Angola', component: AO },
  antarctica: { name: 'Antarctica', component: AQ },
  argentina: { name: 'Argentina', component: AR },
  americanSamoa: { name: 'American Samoa', component: AS },
  austria: { name: 'Austria', component: AT },
  australia: { name: 'Australia', component: AU },
  aruba: { name: 'Aruba', component: AW },
  alandIslands: { name: 'Åland Islands', component: AX },
  azerbaijan: { name: 'Azerbaijan', component: AZ },
  bosniaAndHerzegovina: { name: 'Bosnia and Herzegovina', component: BA },
  barbados: { name: 'Barbados', component: BB },
  bangladesh: { name: 'Bangladesh', component: BD },
  belgium: { name: 'Belgium', component: BE },
  burkinaFaso: { name: 'Burkina Faso', component: BF },
  bulgaria: { name: 'Bulgaria', component: BG },
  bahrain: { name: 'Bahrain', component: BH },
  burundi: { name: 'Burundi', component: BI },
  benin: { name: 'Benin', component: BJ },
  saintBarthelemy: { name: 'Saint Barthélemy', component: BL },
  bermuda: { name: 'Bermuda', component: BM },
  brunei: { name: 'Brunei Darussalam', component: BN },
  bolivia: { name: 'Bolivia', component: BO },
  bonaire: { name: 'Bonaire, Sint Eustatius and Saba', component: BQ },
  brazil: { name: 'Brazil', component: BR },
  bahamas: { name: 'Bahamas', component: BS },
  bhutan: { name: 'Bhutan', component: BT },
  bouvetIsland: { name: 'Bouvet Island', component: BV },
  botswana: { name: 'Botswana', component: BW },
  belarus: { name: 'Belarus', component: BY },
  belize: { name: 'Belize', component: BZ },
  canada: { name: 'Canada', component: CA },
  cocosIslands: { name: 'Cocos (Keeling) Islands', component: CC },
  congoDR: { name: 'Congo, Democratic Republic of the', component: CD },
  centralAfricanRepublic: { name: 'Central African Republic', component: CF },
  congo: { name: 'Congo', component: CG },
  switzerland: { name: 'Switzerland', component: CH },
  coteIvoire: { name: "Cote d'Ivoire", component: CI },
  cookIslands: { name: 'Cook Islands', component: CK },
  chile: { name: 'Chile', component: CL },
  cameroon: { name: 'Cameroon', component: CM },
  china: { name: 'China', component: CN },
  colombia: { name: 'Colombia', component: CO },
  costaRica: { name: 'Costa Rica', component: CR },
  cuba: { name: 'Cuba', component: CU },
  capeVerde: { name: 'Cape Verde', component: CV },
  curacao: { name: 'Curaçao', component: CW },
  christmasIsland: { name: 'Christmas Island', component: CX },
  cyprus: { name: 'Cyprus', component: CY },
  czechRepublic: { name: 'Czech Republic', component: CZ },
  germany: { name: 'Germany', component: DE },
  djibouti: { name: 'Djibouti', component: DJ },
  denmark: { name: 'Denmark', component: DK },
  dominica: { name: 'Dominica', component: DM },
  dominicanRepublic: { name: 'Dominican Republic', component: DO },
  algeria: { name: 'Algeria', component: DZ },
  ecuador: { name: 'Ecuador', component: EC },
  estonia: { name: 'Estonia', component: EE },
  egypt: { name: 'Egypt', component: EG },
  westernSahara: { name: 'Western Sahara', component: EH },
  eritrea: { name: 'Eritrea', component: ER },
  spain: { name: 'Spain', component: ES },
  ethiopia: { name: 'Ethiopia', component: ET },
  europeanUnion: { name: 'European Union', component: EU },
  finland: { name: 'Finland', component: FI },
  fiji: { name: 'Fiji', component: FJ },
  falklandIslands: { name: 'Falkland Islands', component: FK },
  micronesia: { name: 'Federated States of Micronesia', component: FM },
  faroeIslands: { name: 'Faroe Islands', component: FO },
  france: { name: 'France', component: FR },
  gabon: { name: 'Gabon', component: GA },
  unitedKingdom: { name: 'United Kingdom', component: GB },
  grenada: { name: 'Grenada', component: GD },
  georgia: { name: 'Georgia', component: GE },
  frenchGuiana: { name: 'French Guiana', component: GF },
  guernsey: { name: 'Guernsey', component: GG },
  ghana: { name: 'Ghana', component: GH },
  gibraltar: { name: 'Gibraltar', component: GI },
  greenland: { name: 'Greenland', component: GL },
  gambia: { name: 'Gambia', component: GM },
  guinea: { name: 'Guinea', component: GN },
  guadeloupe: { name: 'Guadeloupe', component: GP },
  equatorialGuinea: { name: 'Equatorial Guinea', component: GQ },
  greece: { name: 'Greece', component: GR },
  southGeorgia: {
    name: 'South Georgia and the South Sandwich Islands',
    component: GS,
  },
  guatemala: { name: 'Guatemala', component: GT },
  guam: { name: 'Guam', component: GU },
  guineaBissau: { name: 'Guinea-Bissau', component: GW },
  guyana: { name: 'Guyana', component: GY },
  hongKong: { name: 'Hong Kong', component: HK },
  heardIsland: { name: 'Heard Island and McDonald Islands', component: HM },
  honduras: { name: 'Honduras', component: HN },
  croatia: { name: 'Croatia', component: HR },
  haiti: { name: 'Haiti', component: HT },
  hungary: { name: 'Hungary', component: HU },
  canaryIslands: { name: 'Canary Islands', component: IC },
  indonesia: { name: 'Indonesia', component: ID },
  ireland: { name: 'Ireland', component: IE },
  israel: { name: 'Israel', component: IL },
  isleOfMan: { name: 'Isle of Man', component: IM },
  india: { name: 'India', component: IN },
  britishIndianOceanTerritory: {
    name: 'British Indian Ocean Territory',
    component: IO,
  },
  iraq: { name: 'Iraq', component: IQ },
  iran: { name: 'Iran', component: IR },
  iceland: { name: 'Iceland', component: IS },
  italy: { name: 'Italy', component: IT },
  jersey: { name: 'Jersey', component: JE },
  jamaica: { name: 'Jamaica', component: JM },
  jordan: { name: 'Jordan', component: JO },
  japan: { name: 'Japan', component: JP },
  kenya: { name: 'Kenya', component: KE },
  kyrgyzstan: { name: 'Kyrgyzstan', component: KG },
  cambodia: { name: 'Cambodia', component: KH },
  kiribati: { name: 'Kiribati', component: KI },
  comoros: { name: 'Comoros', component: KM },
  saintKittsAndNevis: { name: 'Saint Kitts and Nevis', component: KN },
  northKorea: { name: 'North Korea', component: KP },
  southKorea: { name: 'South Korea', component: KR },
  kuwait: { name: 'Kuwait', component: KW },
  caymanIslands: { name: 'Cayman Islands', component: KY },
  kazakhstan: { name: 'Kazakhstan', component: KZ },
  laos: { name: 'Laos', component: LA },
  lebanon: { name: 'Lebanon', component: LB },
  saintLucia: { name: 'Saint Lucia', component: LC },
  liechtenstein: { name: 'Liechtenstein', component: LI },
  sriLanka: { name: 'Sri Lanka', component: LK },
  liberia: { name: 'Liberia', component: LR },
  lesotho: { name: 'Lesotho', component: LS },
  lithuania: { name: 'Lithuania', component: LT },
  luxembourg: { name: 'Luxembourg', component: LU },
  latvia: { name: 'Latvia', component: LV },
  libya: { name: 'Libya', component: LY },
  morocco: { name: 'Morocco', component: MA },
  monaco: { name: 'Monaco', component: MC },
  moldova: { name: 'Moldova', component: MD },
  montenegro: { name: 'Montenegro', component: ME },
  saintMartin: { name: 'Saint Martin (French Part)', component: MF },
  madagascar: { name: 'Madagascar', component: MG },
  marshallIslands: { name: 'Marshall Islands', component: MH },
  northMacedonia: { name: 'North Macedonia', component: MK },
  mali: { name: 'Mali', component: ML },
  myanmar: { name: 'Burma', component: MM },
  mongolia: { name: 'Mongolia', component: MN },
  macao: { name: 'Macao', component: MO },
  northernMarianaIslands: { name: 'Northern Mariana Islands', component: MP },
  martinique: { name: 'Martinique', component: MQ },
  mauritania: { name: 'Mauritania', component: MR },
  montserrat: { name: 'Montserrat', component: MS },
  malta: { name: 'Malta', component: MT },
  mauritius: { name: 'Mauritius', component: MU },
  maldives: { name: 'Maldives', component: MV },
  malawi: { name: 'Malawi', component: MW },
  mexico: { name: 'Mexico', component: MX },
  malaysia: { name: 'Malaysia', component: MY },
  mozambique: { name: 'Mozambique', component: MZ },
  namibia: { name: 'Namibia', component: NA },
  newCaledonia: { name: 'New Caledonia', component: NC },
  niger: { name: 'Niger', component: NE },
  norfolkIsland: { name: 'Norfolk Island', component: NF },
  nigeria: { name: 'Nigeria', component: NG },
  nicaragua: { name: 'Nicaragua', component: NI },
  netherlands: { name: 'Netherlands', component: NL },
  norway: { name: 'Norway', component: NO },
  nepal: { name: 'Nepal', component: NP },
  nauru: { name: 'Nauru', component: NR },
  niue: { name: 'Niue', component: NU },
  newZealand: { name: 'New Zealand', component: NZ },
  oman: { name: 'Oman', component: OM },
  panama: { name: 'Panama', component: PA },
  peru: { name: 'Peru', component: PE },
  frenchPolynesia: { name: 'French Polynesia', component: PF },
  papuaNewGuinea: { name: 'Papua New Guinea', component: PG },
  philippines: { name: 'Philippines', component: PH },
  pakistan: { name: 'Pakistan', component: PK },
  poland: { name: 'Poland', component: PL },
  saintPierreMiquelon: { name: 'Saint Pierre and Miquelon', component: PM },
  pitcairn: { name: 'Pitcairn', component: PN },
  puertoRico: { name: 'Puerto Rico', component: PR },
  palestine: { name: 'Palestine', component: PS },
  portugal: { name: 'Portugal', component: PT },
  palau: { name: 'Palau', component: PW },
  paraguay: { name: 'Paraguay', component: PY },
  qatar: { name: 'Qatar', component: QA },
  reunion: { name: 'Reunion', component: RE },
  romania: { name: 'Romania', component: RO },
  serbia: { name: 'Serbia', component: RS },
  russia: { name: 'Russia', component: RU },
  rwanda: { name: 'Rwanda', component: RW },
  saudiArabia: { name: 'Saudi Arabia', component: SA },
  solomonIslands: { name: 'Solomon Islands', component: SB },
  seychelles: { name: 'Seychelles', component: SC },
  sudan: { name: 'Sudan', component: SD },
  sweden: { name: 'Sweden', component: SE },
  singapore: { name: 'Singapore', component: SG },
  saintHelena: { name: 'Saint Helena', component: SH },
  slovenia: { name: 'Slovenia', component: SI },
  svalbardJanMayen: { name: 'Svalbard and Jan Mayen', component: SJ },
  slovakia: { name: 'Slovakia', component: SK },
  sierraLeone: { name: 'Sierra Leone', component: SL },
  sanMarino: { name: 'San Marino', component: SM },
  senegal: { name: 'Senegal', component: SN },
  somalia: { name: 'Somalia', component: SO },
  suriname: { name: 'Suriname', component: SR },
  southSudan: { name: 'South Sudan', component: SS },
  saoTomePrincipe: { name: 'Sao Tome and Principe', component: ST },
  elSalvador: { name: 'El Salvador', component: SV },
  sintMaarten: { name: 'Sint Maarten', component: SX },
  syria: { name: 'Syria', component: SY },
  swaziland: { name: 'Swaziland', component: SZ },
  tristanDaCunha: { name: 'Tristan da Cunha', component: TA },
  turksAndCaicos: { name: 'Turks and Caicos Islands', component: TC },
  chad: { name: 'Chad', component: TD },
  frenchSouthernTerritories: {
    name: 'French Southern Territories',
    component: TF,
  },
  togo: { name: 'Togo', component: TG },
  thailand: { name: 'Thailand', component: TH },
  tajikistan: { name: 'Tajikistan', component: TJ },
  tokelau: { name: 'Tokelau', component: TK },
  timorLeste: { name: 'Timor-Leste', component: TL },
  turkmenistan: { name: 'Turkmenistan', component: TM },
  tunisia: { name: 'Tunisia', component: TN },
  tonga: { name: 'Tonga', component: TO },
  turkey: { name: 'Turkey', component: TR },
  trinidadAndTobago: { name: 'Trinidad and Tobago', component: TT },
  tuvalu: { name: 'Tuvalu', component: TV },
  taiwan: { name: 'Taiwan', component: TW },
  tanzania: { name: 'Tanzania', component: TZ },
  ukraine: { name: 'Ukraine', component: UA },
  uganda: { name: 'Uganda', component: UG },
  usMinorOutlyingIslands: {
    name: 'United States Minor Outlying Islands',
    component: UM,
  },
  unitedStates: { name: 'United States', component: US },
  uruguay: { name: 'Uruguay', component: UY },
  uzbekistan: { name: 'Uzbekistan', component: UZ },
  vaticanCity: { name: 'Holy See (Vatican City State)', component: VA },
  saintVincent: { name: 'Saint Vincent and the Grenadines', component: VC },
  venezuela: { name: 'Venezuela', component: VE },
  britishVirginIslands: { name: 'Virgin Islands, British', component: VG },
  usVirginIslands: { name: 'Virgin Islands, U.S.', component: VI },
  vietnam: { name: 'Vietnam', component: VN },
  vanuatu: { name: 'Vanuatu', component: VU },
  wallisFutuna: { name: 'Wallis and Futuna', component: WF },
  samoa: { name: 'Samoa', component: WS },
  kosovo: { name: 'Kosovo', component: XK },
  yemen: { name: 'Yemen', component: YE },
  mayotte: { name: 'Mayotte', component: YT },
  southAfrica: { name: 'South Africa', component: ZA },
  zambia: { name: 'Zambia', component: ZM },
  zimbabwe: { name: 'Zimbabwe', component: ZW },
} as const
